# pull official base image
FROM  artifactory.manulife.ca/endorsed-docker/ets-node:20-debian12-2.7.0

#set node env as PRODUCTION
ENV NODE_ENV production

WORKDIR /home/node

# copy .npmrc to get npm packages from Manulife Artifactory
COPY --chown=node:node .npmrc ./

# copy package.json and package-lock.json to get dependencies
COPY --chown=node:node package*.json ./

# install npm dependencies except dev dependencies
RUN npm ci --omit=dev

RUN rm .npmrc

# copy the rest of files (unless ignored in .dockerignore)
COPY --chown=node:node src ./src
COPY --chown=node:node public ./public
COPY --chown=node:node .env ./

# describe that the container is listening on port 3000
EXPOSE 3000

# start container with npm run start
CMD [ "npm", "run", "start" ]