# build environment
FROM node:alpine as builder
WORKDIR /app
COPY ./package.json /app
COPY ./package-lock.json /app
COPY . .
RUN npm ci --silent
RUN npm run build

# production environment
FROM nginx:stable-alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
