apiVersion: apps/v1
kind: Deployment
metadata:
  name: banksch-mu-aks-ui
  namespace: banksch
  labels:
    app: banksch-mu-aks-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banksch-mu-aks-ui
  template:
    metadata:
      labels:
        app: banksch-mu-aks-ui
    spec:
      nodeSelector:
        'kubernetes.io/os': linux
      containers:
        - name: banksch-mu-aks-ui
          image: acrmuaksbankschdev.azurecr.io/banksch-mu-aks-ui:1.0
          resources:
            limits:
              memory: '64Mi'
              cpu: '100m'
          ports:
            - containerPort: 8080
          env:
            - name: API_URL
              value: 'http://10.56.46.32:3001/api'