apiVersion: apps/v1
kind: Deployment
metadata:
  name: coach-mu-aks-react
  namespace: coach
  labels:
    app: coach-mu-aks-react
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coach-mu-aks-react
  template:
    metadata:
      labels:
        app: coach-mu-aks-react
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: coach-mu-aks-react
          image: coach-mu-aks-react:1.0
          resources:
            limits:
              memory: '64Mi'
              cpu: '100m'
          ports:
            - containerPort: 80
          env:
            - name: HELLO
              value: 'world'
