# Artifactory
releaseRepo: mfc-mu-npm

# Node
projectType: static
nodeBuildCommand: npm ci
nodePackageCommand: npm run build

# Version
increasePatchVersion: true

# Sonar - Disable for lab exercises only
sonarQubeFailPipelineOnFailedQualityGate: false

# SNYK - Disable for lab exercises only
snykGatingEnabled: false